### ISSUE TITLE
plot_epochs throws an error

### ISSUE THREAD

**Issue by lorrandal** [autoreject/autoreject#17]
Hi everyone, I'm getting this error when using plot_epochs from autoreject.

```plot_epochs(epochs_clean, bad_epochs_idx=ar.bad_epochs_idx, fix_log=ar.fix_log.as_matrix(),scalings=dict(eeg=40e-6), title='')
Traceback (most recent call last):

  File "<ipython-input-19-0dc82ca5b4c1>", line 1, in <module>
    plot_epochs(epochs_clean, bad_epochs_idx=ar.bad_epochs_idx, fix_log=ar.fix_log.as_matrix(),scalings=dict(eeg=40e-6), title='')

  File "C:\Users\alfine-l\AppData\Local\Continuum\Anaconda2\lib\site-packages\autoreject\viz.py", line 201, in plot_epochs
    title, picks)

  File "C:\Users\alfine-l\AppData\Local\Continuum\Anaconda2\lib\site-packages\autoreject\viz.py", line 439, in _prepare_mne_browse_epochs
    params['colors'][ch_idx][epoch_idx] = (1., 0., 0., 1.)

IndexError: list assignment index out of range
```

I've installed autoreject using pip following the procedure on http://autoreject.github.io/
The version of mne is 0.13.1  on Anaconda - Spyder (Python 2.7) 64-bit, on w7 64-bit.

The error pops out when trying execute the last line:
```ids = [140,150,160,170,190]
t = (-0.5,1.5)
consense = np.arange(.1,.2,.05)
n_interp = [16,32,48]

epochs = mne.Epochs(raw1,events1,ids,tmin=t[0],tmax=t[1],add_eeg_ref=False,preload=True,baseline=None,on_missing='warning')
n = len(epochs.events)
ar = LocalAutoRejectCV(consensus_percs=np.asarray(consense), n_interpolates=np.asarray(n_interp))
epochs_clean = ar.fit_transform(epochs.pick_types(eeg=True, meg=False))

print 'Removed {0} epochs.'.format(n-len(epochs_clean.events))

from autoreject import plot_epochs
plot_epochs(epochs_clean, bad_epochs_idx=ar.bad_epochs_idx, fix_log=ar.fix_log.as_matrix(),scalings=dict(eeg=40e-6), title='')
```

Do you have any of a possible cause?
thank you

**Comment by jasmainak** [comment]
@lorrandal you need to pass `epochs` to `plot_epochs()` rather than `epochs_clean` because the `bad_epochs_idx` are with respect to the `epochs` not the `epochs_clean`. Some epochs might have been dropped ...

**Comment by lorrandal** [comment]
thank you very much, of course this solved my problem!

**Comment by jasmainak** [comment]
great! closing issue
