### ISSUE TITLE
Issue with the function ProgressBar when using AutoReject

### ISSUE THREAD

**Issue by AdrienC21** [autoreject/autoreject#189]
Dear AutoReject team,

When I try to use your library, I encounter en error due to the file \autoreject\utils.py, at the line 183 :
_pbar = ProgressBar(iterable, mesg=desc, spinner=True)_

Apparently, the argument _spinner_ is no longer used when calling the function ProgressBar. After deleting it, I can clean my epochs. Therefore, I humbly suggest you to replace this line with :
_pbar = ProgressBar(iterable, mesg=desc)_

Best regards,

A.C.

**Comment by agramfort** [comment]
what autoreject version are you using?

this *spinner=True is gone in current master apparently*

>

**Comment by AdrienC21** [comment]
I use the version 0.2.1 of autoreject
MNE version : 0.21.0
Python version : 3.7.7

The complete error is :

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\autoreject.py", line 1128, in fit_transform
    return self.fit(epochs).transform(epochs, return_log=return_log)
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\autoreject.py", line 1006, in fit
    self.verbose)
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\autoreject.py", line 763, in _run_local_reject_cv
    local_reject.fit(epochs)
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\autoreject.py", line 679, in fit
    verbose=self.verbose)
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\autoreject.py", line 444, in _compute_thresholds
    dots=dots, verbose=verbose)
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\utils.py", line 239, in _clean_by_interp
    desc=mesg, verbose=verbose)):
  File "c:\users\acarr\miniconda3\lib\site-packages\autoreject\utils.py", line 183, in _pbar
    pbar = ProgressBar(iterable, mesg=desc, spinner=True)
  File "c:\users\acarr\miniconda3\lib\site-packages\mne\utils\progressbar.py", line 83, in __init__
    disable=disable, **kwargs)
  File "c:\users\acarr\miniconda3\lib\site-packages\tqdm\std.py", line 949, in __init__
    TqdmKeyError("Unknown argument(s): " + str(kwargs)))
tqdm.std.TqdmKeyError: "Unknown argument(s): {'spinner': True}"
```

I tried uninstalling and installing autoreject. Still find the same issue. The problem might occur when using PIP to install the package.

**Comment by agramfort** [comment]
can you try:

pip install -U https://api.github.com/repos/autoreject/autoreject/zipball/master

**Comment by AdrienC21** [comment]
It works !

I value the help you've given me, thank you very much :)
