### ISSUE TITLE
Issue import Autoreject

### ISSUE THREAD

**Issue by BaggioMarco** [autoreject/autoreject#200]
Hi,
on python: 3.9, running the line:
`from autoreject import get_rejection_threshold`
generates:
```
Traceback (most recent call last):
  File "<input>", line 15, in <module>
  File "C:\Users\20180043\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\20180043\AppData\Local\Programs\Python\Python39\lib\site-packages\autoreject\__init__.py", line 3, in <module>
    from .autoreject import _GlobalAutoReject, _AutoReject, AutoReject
  File "C:\Users\20180043\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\20180043\AppData\Local\Programs\Python\Python39\lib\site-packages\autoreject\autoreject.py", line 13, in <module>
    from joblib import Parallel, delayed
  File "C:\Users\20180043\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'joblib'
```

I tried also to update to the development version but same problem happens. It was not happening in python 3.7.
Could you help?
PS: I've a couple of questions about the usage of autoreject, where could I ask you them? Thank you

**Comment by BaggioMarco** [comment]
I'm sorry, my fault, I was missing scikit-learn. Now it works, Thank you

**Comment by jasmainak** [comment]
You can ask your questions here if you want
